### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by mxmkeep** [mirekdusin/Prometheus-Wireguard-Exporter#1]
in function extract_metrics_from_wg_output()
some peers not handshake at all, will meet "IndexError: list index out of range" error
code need to fixed like
               'active': 1 if len(fields) > 5 and (time.time() - int(fields[5])) <= 125 else 0,
                'last_handshake': int(fields[5]) if len(fields) > 5 else 0,
                'received': int(fields[6]) if len(fields) > 6 else 0,
                'sent': int(fields[7]) if len(fields) > 7 else 0

**Comment by mirekdusin** [comment]
Hi Matt, thank you for opening the issue regarding the `IndexError` in the `extract_metrics_from_wg_output` method.

I have updated the method to include your suggested checks for the length of the `fields` list before accessing its elements. This should prevent any `IndexError` from occurring due to missing data for peers without a handshake.
